### ISSUE TITLE
Volume calculation

### ISSUE THREAD

**Issue by shubham9436** [giswqs/lidar#3]
Is there any way to calculate total volume of the DEM?

**Comment by giswqs** [comment]
@shubham9436 Do you mean the total volume of depressions? The volume of each depression is recorded in the output csv file. You can sum up the volume column to get the total volume.

**Comment by shubham9436** [comment]
Not the volume of depression but the volume of the whole DEM.

**Comment by giswqs** [comment]
What's your baseline? I don't think you can calculate the volume of a DEM without defining the baseline. What's your purpose of calculating the volume of the whole DEM?

**Comment by shubham9436** [comment]
I wanted to calculate the volume above ground level of the DEM. Suppose, for example, I have stockpiles in my DEM. So, baseline could be taken as ground level.

**Comment by giswqs** [comment]
You need to define the elevation of the ground level, then use the following formula to calculate volume:

`volume = (DEM - ground-level-elevation) * (cell-size^2)`

**Comment by shubham9436** [comment]
I think you meant sum of `(DEM - ground-level-elevation) * (cell-size^2)`

**Comment by giswqs** [comment]
Correct.
