### ISSUE TITLE
Environment issue 

### ISSUE THREAD

**Issue by maryloooh** [giswqs/lidar#6]
* lidar version: newest
* Python version: 3.7
* Operating System: Windows 10

Hi. First of all, I'm quite a novice using python, so this may be a very simply issue but I'm stuck despite all the forums I checked already! 

So, I installed the lidar package according to the instructions using Anaconda Prompt. It was successful. However, when I tried installing spyder inside that new environment it does not work. I thought I installed spyder successfully also in the new environment but cannot access it (see screenshots below). I can open spyder directly but then it is still in another environment and won't let me access the lidar package. Any thoughts? 

Thanks a lot!

![python_code](https://user-images.githubusercontent.com/56376923/73049483-76754680-3ec8-11ea-9522-8beeac38b017.JPG)

```

**Comment by aubreymoore** [comment]
This does not appear to be an issue with the **lidar** package.
Looks like the Spyder IDE was not installed properly in the **py37** virtual environment.
Try using a Jupyter notebook instead of Spyder.

**Comment by giswqs** [comment]
@maryloooh  Try installing Jupyter Notebook using `conda install notebook`. You can also try [Visual Studio Code](https://code.visualstudio.com/).

**Comment by maryloooh** [comment]
I installed Visual Studio Code and that solved the issue! Thank you both for your response!
