### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by maryloooh** [giswqs/lidar#8]
* lidar version:
* Python version: 3.7
* Operating System: Windows 10

###
RuntimeError: Free disk space available is 49152 bytes, whereas 2705360268 are at least necessary. You can disable this check by defining the CHECK_DISK_FREE_SPACE configuration option to FALSE. 

How can I solve this? Thanks a lot!

**Comment by giswqs** [comment]
How big is your DEM? This error seems to be caused by [GDAL](https://gdal.org/), not the lidar package. See [here](https://trac.osgeo.org/gdal/ticket/7090).

**Comment by maryloooh** [comment]
DEM is 6GB!

Does your program work only with tifs or also other formats? Maybe if I
convert it to GRID it is smaller and might not give an issue?

Thanks,
Maria

**Comment by giswqs** [comment]
The program utilizes the [`LoadGDAL()`](https://richdem.readthedocs.io/en/latest/loading_data.html)  function from the [RichDEM](https://richdem.readthedocs.io/en/latest/index.html) package to read and write data. Therefore, it should be able to handle most common raster formats. If you DEM is too big to process in one round, you can subdivide the DEM into smaller watersheds and use a loop to run the program.

**Comment by maryloooh** [comment]
Thank you for your response! I was able to run it after moving the input
and output data directory to my other drive with more free space.

**Comment by giswqs** [comment]
Good to know. Thanks for the update.
